version: '3.7'

services:
  # nginx - web server
  nginx:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    env_file: &env
      - ./app/.env
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project/app:cached
  # php - personal home page
  php:
    build:
      context: .
      dockerfile: ./docker-config/alpine-php-dev-overlay/Dockerfile
    env_file:
      *env
    expose:
      - "9000"
    volumes:
      - ./app:/var/www/project/app:consistent
